services:
  unstructured-dev:
    build:
      context: ..
      dockerfile: unstructured/Dockerfile
    volumes:
      - ../:/workspace
    ports:
      - "8000:8000"
    command: /bin/bash
    tty: true
    stdin_open: true
